name: leetcode heatmap by dsaStats.site

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Image from API
        run: |
          curl -o image.png https://www.dsastats.site/api/lcheatmap/pranjalpratapsingh1

      - name: Update README.md
        run: |
          # Add or update the image in README.md
          echo "![DevCard](image.png)" > README.md

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update README with new DevCard image'
          add: 'README.md'
