name: Update LeetCode Heatmap

on:
  # every day at 22:00 UTC, plus manual trigger
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  update-heatmap:
    runs-on: ubuntu-latest
    # allow up to 30 minutes for Cloudflare + CAPTCHA solve
    timeout-minutes: 30

    env:
      # Puppeteer/stealth + recaptcha solver
      LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
      TWO_CAPTCHA_KEY:   ${{ secrets.TWO_CAPTCHA_KEY }}
      # pass into your script to bump page.goto / waitForNavigation
      PUPPETEER_TIMEOUT: 120000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Generate & Upscale Heatmap
        # assumes util/lcheatmap.js reads env.LEETCODE_SESSION, env.TWO_CAPTCHA_KEY,
        # env.PUPPETEER_TIMEOUT and writes to ./leetcodeHeatmap.png
        run: |
          node util/lcheatmap.js \
            --username="${{ inputs.username || 'pranjalpratapsingh1' }}" \
            --output="leetcodeHeatmap.png"
        shell: bash

      - name: Verify output
        run: |
          if [ ! -s leetcodeHeatmap.png ]; then
            echo "❌ Heatmap generation failed (empty or missing file)"
            exit 1
          fi

      - name: Commit & Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add leetcodeHeatmap.png
          git diff --quiet && echo "↪ No changes to commit" || git commit -m "🔄 Update LeetCode Heatmap"
          git push
