name: leetcode heatmap by dsaStats.site
on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Image from API
        run: |
          curl -o leetcodeHeatmap.png https://www.dsastats.site/api/lcheatmap/pranjalpratapsingh1

      - name: Commit and Push Image
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update LeetCode Heatmap image'
          add: 'leetcodeHeatmap.png'

