name: leetcode heatmap by dsaStats.site

on:
  schedule:
    - cron: "0 22 * * *" # Runs at 10 PM UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Image from API
        run: |
          curl -o leetcodeHeatmap.png --fail --silent --show-error https://www.dsastats.site/api/lcheatmap/pranjalpratapsingh1
          if [ ! -s leetcodeHeatmap.png ]; then
            echo "No image returned or link inaccessible. Aborting workflow."
            exit 1
          fi

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Pull Latest Changes
        run: |
          git pull --rebase origin main || true

      - name: Commit and Push Image
        run: |
          git add leetcodeHeatmap.png
          git commit -m "Update LeetCode Heatmap image" || echo "No changes to commit"
          git push origin main
